version: '3.8'

services:
  db:
    image: mysql:5.7  # Specify the version you want here
    container_name: mysql_db_beestock
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234  # Change this to your desired root password
      MYSQL_DATABASE: user               # Change this to your desired database name
      MYSQL_USER: mysql                 # Change this to your desired user
      MYSQL_PASSWORD: 1234            # Change this to your desired user's password
    ports:
      - "3306:3306"
    volumes:
      - besstock_data:/var/lib/mysql  # Persist data

volumes:
  besstock_data:
